# ───────────────────────────────────────────────────────────────────────
# export/writers.py — OpenGOAL Level Tools
#
# File writers and patchers: write the GOAL source / JSONC / DGO spec files, patch the engine's level-info.gc and game.gp, generate continue-points, export collision/visibility geometry as GLB.
# ───────────────────────────────────────────────────────────────────────

from __future__ import annotations

import bpy, os, re, json, math, mathutils
from pathlib import Path
from ..data import (
    ENTITY_DEFS, ETYPE_CODE, ETYPE_TPAGES, ETYPE_AG, VERTEX_EXPORT_TYPES,
    NAV_UNSAFE_TYPES, NEEDS_PATH_TYPES, NEEDS_PATHB_TYPES, IS_PROP_TYPES,
    needed_tpages, LUMP_REFERENCE, ACTOR_LINK_DEFS,
    _lump_ref_for_etype, _actor_link_slots, _actor_has_links,
    _actor_links, _actor_get_link, _actor_set_link,
    _actor_remove_link, _build_actor_link_lumps,
    _parse_lump_row, _aggro_event_id, AGGRO_TRIGGER_EVENTS,
    _LUMP_HARDCODED_KEYS, _is_custom_type,
)
from ..collections import (
    _get_level_prop, _level_objects,
    _active_level_col, _classify_object, _col_path_for_entity,
    _ensure_sub_collection, _recursive_col_objects,
    _COL_PATH_WAYPOINTS, _COL_PATH_NAVMESHES,
)
from ..collections import (
    _COL_PATH_SPAWNABLE_ENEMIES, _COL_PATH_SPAWNABLE_PLATFORMS,
    _COL_PATH_SPAWNABLE_PROPS, _COL_PATH_SPAWNABLE_NPCS,
    _COL_PATH_SPAWNABLE_PICKUPS, _COL_PATH_TRIGGERS, _COL_PATH_CAMERAS,
    _COL_PATH_SPAWNS, _COL_PATH_SOUND_EMITTERS, _COL_PATH_GEO_SOLID,
    _COL_PATH_GEO_COLLISION, _COL_PATH_GEO_VISUAL, _COL_PATH_GEO_REFERENCE,
    _COL_PATH_WAYPOINTS, _COL_PATH_NAVMESHES,
    _ENTITY_CAT_TO_COL_PATH, _LEVEL_COL_DEFAULTS,
    _all_level_collections, _active_level_col, _col_is_no_export,
    _recursive_col_objects, _level_objects, _ensure_sub_collection,
    _link_object_to_sub_collection, _col_path_for_entity, _classify_object,
    _get_level_prop, _set_level_prop, _active_level_items,
    _set_blender_active_collection, _get_death_plane, _set_death_plane,
    _on_active_level_changed,
)

# Cross-module imports (siblings in the export package)
from .levels import (
    needed_ags,
)
from .paths import (
    _game_gp,
    _goal_src,
    _iso,
    _ldir,
    _level_info,
    _nick,
    log,
)


# Cross-module imports (siblings in the export package)


def write_gc(name, has_triggers=False, has_checkpoints=False, has_aggro_triggers=False, has_custom_triggers=False, scene=None):
    """Write obs.gc: always emits camera-marker type; if has_triggers also
    emits camera-trigger type; if has_checkpoints emits checkpoint-trigger type;
    if has_aggro_triggers emits aggro-trigger type;
    if has_custom_triggers emits vol-trigger type (sends 'trigger/'untrigger to custom actors).
    If scene is provided, any ACTOR_ empties with an og_goal_code_ref text block
    assigned (and enabled) have their code appended after the addon's types.
    All types birth automatically via entity-actor.birth! — no nREPL needed.
    """
    d = _goal_src() / "levels" / name
    d.mkdir(parents=True, exist_ok=True)
    p = d / f"{name}-obs.gc"

    lines = [
        ";;-*-Lisp-*-",
        "(in-package goal)",
        f";; {name}-obs.gc -- auto-generated by OpenGOAL Level Tools",
        "",
        ";; camera-marker: inert entity that holds camera position/rotation.",
        "(deftype camera-marker (process-drawable)",
        "  ()",
        "  (:states camera-marker-idle))",
        "",
        "(defstate camera-marker-idle (camera-marker)",
        "  :code (behavior () (loop (suspend))))",
        "",
        "(defmethod init-from-entity! ((this camera-marker) (arg0 entity-actor))",
        "  (set! (-> this root) (new (quote process) (quote trsqv)))",
        "  (process-drawable-from-entity! this arg0)",
        "  (go camera-marker-idle)",
        "  (none))",
        "",
    ]

    if has_triggers:
        lines += [
            ";; camera-trigger: AABB volume entity that switches the active camera.",
            ";; Reads bounds from meters lumps; reads cam-name string lump.",
            ";; No nREPL call needed -- births automatically on level load.",
            "(deftype camera-trigger (process-drawable)",
            "  ((cam-name    string  :offset-assert 176)",
            "   (cull-radius float   :offset-assert 180)",
            "   (xmin        float   :offset-assert 184)",
            "   (xmax        float   :offset-assert 188)",
            "   (ymin        float   :offset-assert 192)",
            "   (ymax        float   :offset-assert 196)",
            "   (zmin        float   :offset-assert 200)",
            "   (zmax        float   :offset-assert 204)",
            "   (inside      symbol  :offset-assert 208))",
            "  :heap-base #x70",
            "  :size-assert #xd4",
            "  (:states camera-trigger-active))",
            "",
            "(defstate camera-trigger-active (camera-trigger)",
            "  :code",
            "  (behavior ()",
            "    (loop",
            "      (when (and *target* (zero? (mod (-> *display* base-frame-counter) 4)))",
            "        (let* ((pos  (-> *target* control trans))",
            "               (dx   (- (-> pos x) (-> self root trans x)))",
            "               (dy   (- (-> pos y) (-> self root trans y)))",
            "               (dz   (- (-> pos z) (-> self root trans z)))",
            "               (cr   (-> self cull-radius))",
            "               (in-vol (and",
            "                 (< (+ (* dx dx) (* dy dy) (* dz dz)) (* cr cr))",
            "                 (< (-> self xmin) (-> pos x)) (< (-> pos x) (-> self xmax))",
            "                 (< (-> self ymin) (-> pos y)) (< (-> pos y) (-> self ymax))",
            "                 (< (-> self zmin) (-> pos z)) (< (-> pos z) (-> self zmax)))))",
            "          (cond",
            "            ((and in-vol (not (-> self inside)))",
            "             (set! (-> self inside) #t)",
            "             (format 0 \"[cam-trigger] enter -> ~A~%\" (-> self cam-name))",
            "             (send-event *camera* (quote change-to-entity-by-name) (-> self cam-name)))",
            "            ((and (not in-vol) (-> self inside))",
            "             (set! (-> self inside) #f)",
            "             (format 0 \"[cam-trigger] exit ~A~%\" (-> self cam-name))",
            "             (send-event *camera* (quote clear-entity))))))",
            "      (suspend))))",
            "",
            "(defmethod init-from-entity! ((this camera-trigger) (arg0 entity-actor))",
            "  (set! (-> this root) (new (quote process) (quote trsqv)))",
            "  (process-drawable-from-entity! this arg0)",
            "  (set! (-> this cam-name) (res-lump-struct arg0 (quote cam-name) string))",
            "  (set! (-> this xmin) (res-lump-float arg0 (quote bound-xmin)))",
            "  (set! (-> this xmax) (res-lump-float arg0 (quote bound-xmax)))",
            "  (set! (-> this ymin) (res-lump-float arg0 (quote bound-ymin)))",
            "  (set! (-> this ymax) (res-lump-float arg0 (quote bound-ymax)))",
            "  (set! (-> this zmin) (res-lump-float arg0 (quote bound-zmin)))",
            "  (set! (-> this zmax) (res-lump-float arg0 (quote bound-zmax)))",
            "  (let* ((hx (* 0.5 (- (-> this xmax) (-> this xmin))))",
            "         (hy (* 0.5 (- (-> this ymax) (-> this ymin))))",
            "         (hz (* 0.5 (- (-> this zmax) (-> this zmin)))))",
            "    (set! (-> this cull-radius) (sqrtf (+ (* hx hx) (* hy hy) (* hz hz)))))",
            "  (set! (-> this inside) #f)",
            "  (format 0 \"[cam-trigger] armed: ~A cull-r ~M~%\" (-> this cam-name) (-> this cull-radius))",
            "  (go camera-trigger-active)",
            "  (none))",
            "",
        ]
        log(f"  [write_gc] camera-trigger type embedded")

    if has_checkpoints:
        lines += [
            ";; checkpoint-trigger: sets continue point when Jak enters the volume.",
            ";; After firing it enters a 5-second cooldown then re-arms automatically,",
            ";; so if the player dies and respawns in the same zone it fires again.",
            ";; Two modes: sphere (default) or AABB (has-volume lump = 1).",
            "(deftype checkpoint-trigger (process-drawable)",
            "  ((cp-name     string  :offset-assert 176)",
            "   (cull-radius float   :offset-assert 180)",
            "   (radius      float   :offset-assert 184)",
            "   (use-vol     symbol  :offset-assert 188)",
            "   (was-near    symbol  :offset-assert 192)",
            "   (xmin        float   :offset-assert 196)",
            "   (xmax        float   :offset-assert 200)",
            "   (ymin        float   :offset-assert 204)",
            "   (ymax        float   :offset-assert 208)",
            "   (zmin        float   :offset-assert 212)",
            "   (zmax        float   :offset-assert 216))",
            "  :heap-base #x70",
            "  :size-assert #xdc",
            "  (:states checkpoint-trigger-active checkpoint-trigger-wait-exit))",
            "",
            ";; Wait-for-exit state: fired, now waiting for player to leave the volume.",
            ";; Re-arms the moment they step out — zero overhead while inside, instant",
            ";; re-arm on exit. No timer needed.",
            "(defstate checkpoint-trigger-wait-exit (checkpoint-trigger)",
            "  :code",
            "  (behavior ()",
            "    (loop",
            "      (when (and *target* (zero? (mod (-> *display* base-frame-counter) 4)))",
            "        (let* ((pos  (-> *target* control trans))",
            "               (dx   (- (-> pos x) (-> self root trans x)))",
            "               (dy   (- (-> pos y) (-> self root trans y)))",
            "               (dz   (- (-> pos z) (-> self root trans z)))",
            "               (cr   (-> self cull-radius))",
            "               (still-inside (and",
            "                 (< (+ (* dx dx) (* dy dy) (* dz dz)) (* cr cr))",
            "                 (if (-> self use-vol)",
            "                   (and",
            "                     (< (-> self xmin) (-> pos x)) (< (-> pos x) (-> self xmax))",
            "                     (< (-> self ymin) (-> pos y)) (< (-> pos y) (-> self ymax))",
            "                     (< (-> self zmin) (-> pos z)) (< (-> pos z) (-> self zmax)))",
            "                   (let ((r (-> self radius)))",
            "                     (< (+ (* dx dx) (* dy dy) (* dz dz)) (* r r)))))))",
            "          (when (not still-inside)",
            "            (format 0 \"[cp-trigger] ~A re-armed~%\" (-> self cp-name))",
            "            (go checkpoint-trigger-active))))",
            "      (suspend))))",
            "",
            "(defstate checkpoint-trigger-active (checkpoint-trigger)",
            "  :code",
            "  (behavior ()",
            "    (loop",
            "      (when (and *target* (zero? (mod (-> *display* base-frame-counter) 4)))",
            "        (let* ((pos  (-> *target* control trans))",
            "               (dx   (- (-> pos x) (-> self root trans x)))",
            "               (dy   (- (-> pos y) (-> self root trans y)))",
            "               (dz   (- (-> pos z) (-> self root trans z)))",
            "               (cr   (-> self cull-radius))",
            "               (near (< (+ (* dx dx) (* dy dy) (* dz dz)) (* cr cr)))",
            "               (inside (and near",
            "                 (if (-> self use-vol)",
            "                   (and",
            "                     (< (-> self xmin) (-> pos x)) (< (-> pos x) (-> self xmax))",
            "                     (< (-> self ymin) (-> pos y)) (< (-> pos y) (-> self ymax))",
            "                     (< (-> self zmin) (-> pos z)) (< (-> pos z) (-> self zmax)))",
            "                   (let ((r (-> self radius)))",
            "                     (< (+ (* dx dx) (* dy dy) (* dz dz)) (* r r)))))))",
            "          (when (and near (not inside) (not (-> self was-near)))",
            "            (format 0 \"[cp-trigger] ~A sphere-hit AABB-miss~%\" (-> self cp-name)))",
            "          (set! (-> self was-near) near)",
            "          (when inside",
            "            (format 0 \"[cp-trigger] fired -> ~A~%\" (-> self cp-name))",
            "            (set-continue! *game-info* (-> self cp-name))",
            "            (go checkpoint-trigger-wait-exit))))",
            "      (suspend))))",
            "",
            "(defmethod init-from-entity! ((this checkpoint-trigger) (arg0 entity-actor))",
            "  (set! (-> this root) (new (quote process) (quote trsqv)))",
            "  (process-drawable-from-entity! this arg0)",
            "  (set! (-> this cp-name)  (res-lump-struct arg0 (quote continue-name) string))",
            "  (set! (-> this radius)   (res-lump-float  arg0 (quote radius) :default 12288.0))",
            "  (set! (-> this use-vol)  (!= 0 (the int (res-lump-value arg0 (quote has-volume) uint128))))",
            "  (set! (-> this was-near) #f)",
            "  (set! (-> this xmin)     (res-lump-float arg0 (quote bound-xmin)))",
            "  (set! (-> this xmax)     (res-lump-float arg0 (quote bound-xmax)))",
            "  (set! (-> this ymin)     (res-lump-float arg0 (quote bound-ymin)))",
            "  (set! (-> this ymax)     (res-lump-float arg0 (quote bound-ymax)))",
            "  (set! (-> this zmin)     (res-lump-float arg0 (quote bound-zmin)))",
            "  (set! (-> this zmax)     (res-lump-float arg0 (quote bound-zmax)))",
            "  (let* ((hx (* 0.5 (- (-> this xmax) (-> this xmin))))",
            "         (hy (* 0.5 (- (-> this ymax) (-> this ymin))))",
            "         (hz (* 0.5 (- (-> this zmax) (-> this zmin))))",
            "         (r  (-> this radius)))",
            "    (set! (-> this cull-radius)",
            "      (if (-> this use-vol)",
            "        (sqrtf (+ (* hx hx) (* hy hy) (* hz hz)))",
            "        (* r 1.2))))",
            "  (format 0 \"[cp-trigger] armed: ~A~%\" (-> this cp-name))",
            "  (go checkpoint-trigger-active)",
            "  (none))",
            "",
        ]
        log(f"  [write_gc] checkpoint-trigger type embedded")

    if has_aggro_triggers:
        lines += [
            ";; aggro-trigger: AABB volume entity that sends a wakeup event to a target enemy.",
            ";; On rising edge (player enters volume), looks up target enemy by name via",
            ";; (process-by-ename ...) and sends one of three quoted symbols based on event-id:",
            ";;   0 = 'cue-chase        — wake enemy + chase player",
            ";;   1 = 'cue-patrol       — return to patrol",
            ";;   2 = 'go-wait-for-cue  — freeze until next cue",
            ";; Re-fires every time the player re-enters (inside flag clears on exit).",
            ";; Only nav-enemies respond to these events (engine: nav-enemy.gc line 142).",
            "(deftype aggro-trigger (process-drawable)",
            "  ((target-name string  :offset-assert 176)",
            "   (cull-radius float   :offset-assert 180)",
            "   (event-id    int32   :offset-assert 184)",
            "   (xmin        float   :offset-assert 188)",
            "   (xmax        float   :offset-assert 192)",
            "   (ymin        float   :offset-assert 196)",
            "   (ymax        float   :offset-assert 200)",
            "   (zmin        float   :offset-assert 204)",
            "   (zmax        float   :offset-assert 208)",
            "   (inside      symbol  :offset-assert 212))",
            "  :heap-base #x70",
            "  :size-assert #xd8",
            "  (:states aggro-trigger-active))",
            "",
            "(defstate aggro-trigger-active (aggro-trigger)",
            "  :code",
            "  (behavior ()",
            "    (loop",
            "      (when (and *target* (zero? (mod (-> *display* base-frame-counter) 4)))",
            "        (let* ((pos  (-> *target* control trans))",
            "               (dx   (- (-> pos x) (-> self root trans x)))",
            "               (dy   (- (-> pos y) (-> self root trans y)))",
            "               (dz   (- (-> pos z) (-> self root trans z)))",
            "               (cr   (-> self cull-radius))",
            "               (in-vol (and",
            "                 (< (+ (* dx dx) (* dy dy) (* dz dz)) (* cr cr))",
            "                 (< (-> self xmin) (-> pos x)) (< (-> pos x) (-> self xmax))",
            "                 (< (-> self ymin) (-> pos y)) (< (-> pos y) (-> self ymax))",
            "                 (< (-> self zmin) (-> pos z)) (< (-> pos z) (-> self zmax)))))",
            "          (cond",
            "            ((and in-vol (not (-> self inside)))",
            "             (set! (-> self inside) #t)",
            "             (format 0 \"[aggro-trigger] enter -> ~A~%\" (-> self target-name))",
            "             (let ((proc (process-by-ename (-> self target-name))))",
            "               (when proc",
            "                 (cond",
            "                   ((zero? (-> self event-id))",
            "                    (send-event proc 'cue-chase))",
            "                   ((= (-> self event-id) 1)",
            "                    (send-event proc 'cue-patrol))",
            "                   ((= (-> self event-id) 2)",
            "                    (send-event proc 'go-wait-for-cue))))))",
            "            ((and (not in-vol) (-> self inside))",
            "             (set! (-> self inside) #f)",
            "             (format 0 \"[aggro-trigger] exit ~A~%\" (-> self target-name))))))",
            "      (suspend))))",
            "",
            "(defmethod init-from-entity! ((this aggro-trigger) (arg0 entity-actor))",
            "  (set! (-> this root) (new (quote process) (quote trsqv)))",
            "  (process-drawable-from-entity! this arg0)",
            "  (set! (-> this target-name) (res-lump-struct arg0 (quote target-name) string))",
            "  (set! (-> this event-id)    (the int (res-lump-value arg0 (quote event-id) uint128)))",
            "  (set! (-> this xmin)        (res-lump-float arg0 (quote bound-xmin)))",
            "  (set! (-> this xmax)        (res-lump-float arg0 (quote bound-xmax)))",
            "  (set! (-> this ymin)        (res-lump-float arg0 (quote bound-ymin)))",
            "  (set! (-> this ymax)        (res-lump-float arg0 (quote bound-ymax)))",
            "  (set! (-> this zmin)        (res-lump-float arg0 (quote bound-zmin)))",
            "  (set! (-> this zmax)        (res-lump-float arg0 (quote bound-zmax)))",
            "  (set! (-> this inside)      #f)",
            "  (let* ((hx (* 0.5 (- (-> this xmax) (-> this xmin))))",
            "         (hy (* 0.5 (- (-> this ymax) (-> this ymin))))",
            "         (hz (* 0.5 (- (-> this zmax) (-> this zmin)))))",
            "    (set! (-> this cull-radius) (sqrtf (+ (* hx hx) (* hy hy) (* hz hz)))))",
            "  (format 0 \"[aggro-trigger] armed: ~A cull-r ~M~%\" (-> this target-name) (-> this cull-radius))",
            "  (go aggro-trigger-active)",
            "  (none))",
            "",
        ]
        log(f"  [write_gc] aggro-trigger type embedded")

    if has_custom_triggers:
        lines += [
            ";; vol-trigger: AABB volume entity that sends 'trigger/'untrigger to a custom actor.",
            ";; On rising edge (player enters volume), sends 'trigger to target by name.",
            ";; On falling edge (player exits volume), sends 'untrigger to target by name.",
            ";; Target is looked up each poll via process-by-ename — safe if target dies.",
            ";; Mirrors the aggro-trigger pattern (proven working): *target* guard + frame throttle.",
            "(deftype vol-trigger (process-drawable)",
            "  ((target-name string  :offset-assert 176)",
            "   (cull-radius float   :offset-assert 180)",
            "   (xmin        float   :offset-assert 184)",
            "   (xmax        float   :offset-assert 188)",
            "   (ymin        float   :offset-assert 192)",
            "   (ymax        float   :offset-assert 196)",
            "   (zmin        float   :offset-assert 200)",
            "   (zmax        float   :offset-assert 204)",
            "   (inside      symbol  :offset-assert 208))",
            "  :heap-base #x70",
            "  :size-assert #xd4",
            "  (:states vol-trigger-active))",
            "",
            "(defstate vol-trigger-active (vol-trigger)",
            "  :code",
            "  (behavior ()",
            "    (loop",
            "      (when (and *target* (zero? (mod (-> *display* base-frame-counter) 4)))",
            "        (let* ((pos  (-> *target* control trans))",
            "               (dx   (- (-> pos x) (-> self root trans x)))",
            "               (dy   (- (-> pos y) (-> self root trans y)))",
            "               (dz   (- (-> pos z) (-> self root trans z)))",
            "               (cr   (-> self cull-radius))",
            "               (in-vol (and",
            "                 (< (+ (* dx dx) (* dy dy) (* dz dz)) (* cr cr))",
            "                 (< (-> self xmin) (-> pos x)) (< (-> pos x) (-> self xmax))",
            "                 (< (-> self ymin) (-> pos y)) (< (-> pos y) (-> self ymax))",
            "                 (< (-> self zmin) (-> pos z)) (< (-> pos z) (-> self zmax)))))",
            "          (cond",
            "            ((and in-vol (not (-> self inside)))",
            "             (set! (-> self inside) #t)",
            "             (format 0 \"[vol-trigger] enter -> ~A~%\" (-> self target-name))",
            "             (let ((proc (process-by-ename (-> self target-name))))",
            "               (when proc (send-event proc 'trigger))))",
            "            ((and (not in-vol) (-> self inside))",
            "             (set! (-> self inside) #f)",
            "             (format 0 \"[vol-trigger] exit ~A~%\" (-> self target-name))",
            "             (let ((proc (process-by-ename (-> self target-name))))",
            "               (when proc (send-event proc 'untrigger)))))))",
            "      (suspend))))",
            "",
            "(defmethod init-from-entity! ((this vol-trigger) (arg0 entity-actor))",
            "  (set! (-> this root) (new (quote process) (quote trsqv)))",
            "  (process-drawable-from-entity! this arg0)",
            "  (set! (-> this target-name) (res-lump-struct arg0 (quote target-name) string))",
            "  (set! (-> this xmin)        (res-lump-float arg0 (quote bound-xmin)))",
            "  (set! (-> this xmax)        (res-lump-float arg0 (quote bound-xmax)))",
            "  (set! (-> this ymin)        (res-lump-float arg0 (quote bound-ymin)))",
            "  (set! (-> this ymax)        (res-lump-float arg0 (quote bound-ymax)))",
            "  (set! (-> this zmin)        (res-lump-float arg0 (quote bound-zmin)))",
            "  (set! (-> this zmax)        (res-lump-float arg0 (quote bound-zmax)))",
            "  (set! (-> this inside)      #f)",
            "  (let* ((hx (* 0.5 (- (-> this xmax) (-> this xmin))))",
            "         (hy (* 0.5 (- (-> this ymax) (-> this ymin))))",
            "         (hz (* 0.5 (- (-> this zmax) (-> this zmin)))))",
            "    (set! (-> this cull-radius) (sqrtf (+ (* hx hx) (* hy hy) (* hz hz)))))",
            "  (format 0 \"[vol-trigger] armed -> ~A~%\" (-> this target-name))",
            "  (go vol-trigger-active)",
            "  (none))",
            "",
        ]
        log(f"  [write_gc] vol-trigger type embedded")

    # ── Custom GOAL code injection ────────────────────────────────────────
    # Scan all ACTOR_ empties in the scene for text blocks assigned via
    # og_goal_code_ref.  Deduplicate by text block name so shared blocks are
    # only emitted once.  Each block is appended verbatim after the addon's
    # own generated types.
    if scene is not None:
        seen_blocks   = set()
        custom_blocks = []
        for obj in _level_objects(scene):
            if not (obj.type == "EMPTY"
                    and obj.name.startswith("ACTOR_")
                    and "_wp_" not in obj.name
                    and "_wpb_" not in obj.name):
                continue
            ref = getattr(obj, "og_goal_code_ref", None)
            if ref is None:
                continue
            txt = ref.text_block
            if txt is None or not ref.enabled:
                continue
            if txt.name in seen_blocks:
                continue
            seen_blocks.add(txt.name)
            custom_blocks.append((txt.name, txt.as_string()))

        if custom_blocks:
            lines += [
                "",
                f";; --- custom GOAL code ({len(custom_blocks)} block(s)) ---",
            ]
            for block_name, block_code in custom_blocks:
                lines += [
                    "",
                    f";; block: {block_name}",
                    "",
                ]
                lines += block_code.splitlines()
            log(f"  [write_gc] injected {len(custom_blocks)} custom GOAL code block(s): "
                f"{', '.join(n for n, _ in custom_blocks)}")

    new_text = "\n".join(lines)
    if p.exists() and p.read_text() == new_text:
        log(f"Skipped {p} (unchanged)")
    else:
        p.write_text(new_text)
        log(f"Wrote {p}")

def write_jsonc(name, actors, ambients, camera_actors=None, base_id=10000):
    d = _ldir(name); d.mkdir(parents=True, exist_ok=True)
    all_actors = list(actors) + (camera_actors or [])
    ags = needed_ags(actors)  # camera-tracker has no art group, so only scan regular actors
    data = {
        "long_name": name, "iso_name": _iso(name), "nickname": _nick(name),
        "gltf_file": f"custom_assets/jak1/levels/{name}/{name}.glb",
        "automatic_wall_detection": True, "automatic_wall_angle": 45.0,
        "double_sided_collide": False, "base_id": base_id,
        "art_groups": [g.replace(".go","") for g in ags],
        "custom_models": [], "textures": [["village1-vis-alpha"]],
        "tex_remap": "village1", "sky": "village1", "tpages": [],
        "ambients": ambients, "actors": all_actors,
    }
    p = d / f"{name}.jsonc"
    new_text = f"// OpenGOAL custom level: {name}\n" + json.dumps(data, indent=2)
    if p.exists() and p.read_text() == new_text:
        log(f"Skipped {p} (unchanged)")
    else:
        p.write_text(new_text)
        log(f"Wrote {p}  ({len(actors)} actors + {len(camera_actors or [])} cameras)")

def write_gd(name, ags, code_deps, tpages=None):
    """Write .gd file.

    code_deps is a list of (o_file, gc_path, dep) from needed_code().
    Each enemy .o is inserted before the art groups so it links first.

    FIX v0.5.0 (Bug 1): The opening paren for the inner file list is now its
    own line so that the first file entry keeps correct indentation.  The old
    code concatenated ' (' + files[0].lstrip() which produced a malformed
    S-expression when enemy .o entries were present and caused GOALC to crash.
    """
    d = _ldir(name); d.mkdir(parents=True, exist_ok=True)
    dgo_name = f"{_nick(name).upper()}.DGO"
    code_o   = [f'  "{o}"' for o, _, _ in code_deps]
    # Village1 sky tpages always present; add entity-specific tpages before art groups
    base_tpages = ['  "tpage-398.go"', '  "tpage-400.go"', '  "tpage-399.go"',
                   '  "tpage-401.go"', '  "tpage-1470.go"']
    extra_tpages = [f'  "{tp}"' for tp in (tpages or [])
                    if f'  "{tp}"' not in base_tpages]
    files = (
        [f'  "{name}-obs.o"']
        + code_o
        + base_tpages
        + extra_tpages
        + [f'  "{g}"' for g in ags]
        + [f'  "{name}.go"']
    )
    lines = (
        [f';; DGO for {name}', f'("{dgo_name}"', ' (']
        + files
        + ['  )', ' )']
    )
    p = d / f"{_nick(name)}.gd"
    new_text = "\n".join(lines) + "\n"
    if not p.exists() or p.read_text() != new_text:
        p.write_text(new_text)
        log(f"Wrote {p}  (enemy .o files: {[o for o,_,_ in code_deps]})")
    else:
        log(f"Skipped {p} (unchanged)")

def _make_continues(name, spawns):
    """Build the GOAL :continues list for level-load-info.

    Each spawn dict carries full quat + camera data from collect_spawns.
    Spawns include both SPAWN_ (primary) and CHECKPOINT_ (auto-assigned) empties.

    :vis-nick is intentionally 'none for all custom-level continues.
    Custom levels have no vis data, so vis?=#f at runtime and this field is never
    acted upon. Matches the test-zone reference implementation in level-info.gc.
    """
    def cp(sp):
        cr = sp.get("cam_rot", [1,0,0, 0,1,0, 0,0,1])
        cr_str = " ".join(str(v) for v in cr)
        return (f"(new 'static 'continue-point\n"
                f"             :name \"{name}-{sp['name']}\"\n"
                f"             :level '{name}\n"
                f"             :trans (new 'static 'vector"
                f" :x (meters {sp['x']:.4f}) :y (meters {sp['y']:.4f}) :z (meters {sp['z']:.4f}) :w 1.0)\n"
                f"             :quat (new 'static 'quaternion"
                f" :x {sp.get('qx',0.0)} :y {sp.get('qy',0.0)} :z {sp.get('qz',0.0)} :w {sp.get('qw',1.0)})\n"
                f"             :camera-trans (new 'static 'vector"
                f" :x (meters {sp.get('cam_x', sp['x']):.4f})"
                f" :y (meters {sp.get('cam_y', sp['y']+4.0):.4f})"
                f" :z (meters {sp.get('cam_z', sp['z']):.4f}) :w 1.0)\n"
                f"             :camera-rot (new 'static 'array float 9 {cr_str})\n"
                f"             :load-commands '()\n"
                f"             :vis-nick 'none\n"
                f"             :lev0 '{name}\n"
                f"             :disp0 'display\n"
                f"             :lev1 #f\n"
                f"             :disp1 #f)")

    if spawns:
        return "'(" + "\n             ".join(cp(s) for s in spawns) + ")"

    # No spawns placed — emit a safe default at origin + 10m up
    return (f"'((new 'static 'continue-point\n"
            f"             :name \"{name}-start\"\n"
            f"             :level '{name}\n"
            f"             :trans (new 'static 'vector :x 0.0 :y (meters 10.) :z 0.0 :w 1.0)\n"
            f"             :quat (new 'static 'quaternion :w 1.0)\n"
            f"             :camera-trans (new 'static 'vector :x 0.0 :y (meters 14.) :z 0.0 :w 1.0)\n"
            f"             :camera-rot (new 'static 'array float 9 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0)\n"
            f"             :load-commands '()\n"
            f"             :vis-nick 'none\n"
            f"             :lev0 '{name}\n"
            f"             :disp0 'display\n"
            f"             :lev1 #f\n"
            f"             :disp1 #f))")

def patch_level_info(name, spawns, scene=None):
    p = _level_info()
    if not p.exists(): log(f"WARNING: {p} not found"); return
    # Audio settings from scene props (if scene provided)
    if scene is not None:
        _bank      = str(_get_level_prop(scene, "og_music_bank",    "none") or "none")
        _music_val = f"'{_bank}" if _bank and _bank != "none" else "#f"
        _sb1       = str(_get_level_prop(scene, "og_sound_bank_1",  "none") or "none")
        _sb2       = str(_get_level_prop(scene, "og_sound_bank_2",  "none") or "none")
        _sb_list   = [s for s in [_sb1, _sb2] if s and s != "none"]
        _sbanks    = " ".join(_sb_list)
        _sbanks_val = f"'({_sbanks})" if _sbanks else "'()"
        _bot_h     = float(_get_level_prop(scene, "og_bottom_height", -20.0))
        _vis_ov    = str(_get_level_prop(scene, "og_vis_nick_override", "") or "").strip()
        _vnick     = _vis_ov if _vis_ov else _nick(name)
    else:
        _music_val = "#f"
        _sbanks_val = "'()"
        _bot_h   = -20.0
        _vnick   = _nick(name)

    # ── Auto-compute bsphere from spawn positions ────────────────────────────
    # Centre = mean of all spawn XZ positions, Y = mean spawn Y + 2m.
    # Radius = max distance from centre to any spawn + 64m padding so the
    # engine considers the level "nearby" well before the player reaches it.
    # Fallback when no spawns: a very large sphere (40km radius) that always passes.
    if spawns:
        xs  = [s["x"] for s in spawns]
        ys  = [s["y"] for s in spawns]
        zs  = [s["z"] for s in spawns]
        cx  = sum(xs) / len(xs)
        cy  = sum(ys) / len(ys) + 2.0
        cz  = sum(zs) / len(zs)
        r   = max(
            math.sqrt((s["x"]-cx)**2 + (s["y"]-cy)**2 + (s["z"]-cz)**2)
            for s in spawns
        ) + 64.0
        # Convert to game units (4096 per metre) for the sphere :w value
        bsphere_w = round(r * 4096.0, 1)
        bsphere_str = (f"(new 'static 'sphere"
                       f" :x {round(cx*4096.0, 1)} :y {round(cy*4096.0, 1)} :z {round(cz*4096.0, 1)}"
                       f" :w {bsphere_w})")
    else:
        bsphere_str = "(new 'static 'sphere :w 167772160000.0)"  # ~40km radius

    block = (f"\n(define {name}\n"
             f"  (new 'static 'level-load-info\n"
             f"       :index 27\n"
             f"       :name '{name}\n"
             f"       :visname '{name}-vis\n"
             f"       :nickname '{_vnick}\n"
             f"       :packages '()\n"
             f"       :sound-banks {_sbanks_val}\n"
             f"       :music-bank {_music_val}\n"
             f"       :ambient-sounds '()\n"
             f"       :mood '*village1-mood*\n"
             f"       :mood-func 'update-mood-village1\n"
             f"       :ocean #f\n"
             f"       :sky #t\n"
             f"       :sun-fade 1.0\n"
             f"       :continues\n"
             f"       {_make_continues(name, spawns)}\n"
             f"       :tasks '()\n"
             f"       :priority 100\n"
             f"       :load-commands '()\n"
             f"       :alt-load-commands '()\n"
             f"       :bsp-mask #xffffffffffffffff\n"
             f"       :bsphere {bsphere_str}\n"
             f"       :bottom-height (meters {_bot_h:.1f})\n"
             f"       :run-packages '()\n"
             f"       :wait-for-load #t))\n"
             f"\n(cons! *level-load-list* '{name})\n")
    txt = p.read_text(encoding="utf-8")
    txt = re.sub(rf"\n\(define {re.escape(name)}\b.*?\(cons!.*?'{re.escape(name)}\)\n",
                 "", txt, flags=re.DOTALL)
    marker = ";;;;; CUSTOM LEVELS"
    new_txt = (txt.replace(marker, marker+block, 1) if marker in txt
               else txt + "\n;;;;; CUSTOM LEVELS\n" + block)
    original = p.read_text(encoding="utf-8")
    if new_txt != original:
        p.write_text(new_txt, encoding="utf-8")
        log("Patched level-info.gc")
    else:
        log("Skipped level-info.gc (unchanged)")

def patch_game_gp(name, code_deps=None):
    """Patch game.gp to build our custom level and compile enemy code files.

    code_deps: list of (o_file, gc_path, dep) from needed_code().
    For each enemy type not in GAME.CGO we add a goal-src line so GOALC
    compiles and links its code into our DGO.  Without this the type is
    undefined at runtime and the entity spawns as a do-nothing process.
    """
    p = _game_gp()
    if not p.exists(): log(f"WARNING: {p} not found"); return
    raw  = p.read_bytes()
    crlf = b"\r\n" in raw
    txt  = raw.decode("utf-8").replace("\r\n", "\n")
    nick = _nick(name)
    dgo  = f"{nick.upper()}.DGO"

    # goal-src lines for enemy code (de-duplicated)
    # Skip o_only entries (gc=None) — vanilla game.gp already has their goal-src lines.
    extra_goal_src = ""
    if code_deps:
        seen_gc = set()
        for o, gc, dep in code_deps:
            if gc is None:
                continue  # o_only: .o injected into DGO but no goal-src needed
            if gc not in seen_gc:
                seen_gc.add(gc)
                extra_goal_src += f'(goal-src "{gc}" "{dep}")\n'

    correct_block = (
        f'(build-custom-level "{name}")\n'
        f'(custom-level-cgo "{dgo}" "{name}/{nick}.gd")\n'
        f'(goal-src "levels/{name}/{name}-obs.gc" "process-drawable")\n'
        + extra_goal_src
    )

    # Strip any previously written block for this level
    txt = re.sub(r'\(build-custom-level "' + re.escape(name) + r'"\)\n', '', txt)
    txt = re.sub(r'\(custom-level-cgo "[^"]*" "' + re.escape(name) + r'/[^"]+"\)\n', '', txt)
    # FIX v0.5.0 (Bug 2): was r'/[^"]+\"[^)]*\)' — the \" was a literal
    # backslash+quote so the regex never matched, leaving stale goal-src lines
    # in game.gp across exports which caused duplicate-compile crashes in GOALC.
    txt = re.sub(r'\(goal-src "levels/' + re.escape(name) + r'/[^"]+"[^)]*\)\n', '', txt)
    # Strip ALL enemy goal-src lines that could have been injected by any previous export.
    # This catches leftover entries even if the dep changed between exports.
    # We match any goal-src line whose path matches a known ETYPE_CODE gc file.
    for _etype_info in ETYPE_CODE.values():
        _gc = _etype_info.get("gc", "")
        if _gc:
            txt = re.sub(r'\(goal-src "' + re.escape(_gc) + r'"[^)]*\)\n', '', txt)

    if correct_block in txt:
        log("game.gp already correct"); return

    for anchor in ['(build-custom-level "test-zone")', '(group-list "all-code"']:
        if anchor in txt:
            txt = txt.replace(anchor, correct_block + "\n" + anchor, 1)
            break
    else:
        txt += "\n" + correct_block

    if crlf:
        txt = txt.replace("\n", "\r\n")
    p.write_bytes(txt.encode("utf-8"))
    log(f"Patched game.gp  (extra goal-src: {[gc for _,gc,_ in (code_deps or []) if gc is not None]})")

def export_glb(ctx, name):
    d = _ldir(name); d.mkdir(parents=True, exist_ok=True)

    level_col = _active_level_col(ctx.scene)
    if level_col is not None:
        # Collection mode — export only objects inside the Geometry sub-collection,
        # excluding anything under the Reference sub-collection (og_no_export=True).
        # We select only those objects, export with use_selection=True, then restore.
        geo_col = None
        for c in level_col.children:
            if c.name == "Geometry":
                geo_col = c
                break

        # Gather exportable objects: meshes in Geometry (and its children) except Reference
        if geo_col is not None:
            export_objs = _recursive_col_objects(geo_col, exclude_no_export=True)
            export_objs = [o for o in export_objs if o.type == "MESH"]
        else:
            # No Geometry sub-collection yet — fall back to all meshes in the level.
            # Exclude WATER_ volumes (invisible helpers, not renderable geometry).
            _HELPER_PREFIXES = ("WATER_", "VOL_", "CPVOL_", "NAVMESH_")
            export_objs = [o for o in _recursive_col_objects(level_col, exclude_no_export=True)
                           if o.type == "MESH"
                           and not any(o.name.startswith(p) for p in _HELPER_PREFIXES)
                           and not o.get("og_preview_mesh")
                           and not o.get("og_waypoint_preview_mesh")]

        # Save selection state
        prev_active    = ctx.view_layer.objects.active
        prev_selected  = [o for o in ctx.scene.objects if o.select_get()]

        # Deselect all, select export targets
        for o in ctx.scene.objects:
            o.select_set(False)
        for o in export_objs:
            o.select_set(True)
        if export_objs:
            ctx.view_layer.objects.active = export_objs[0]

        bpy.ops.export_scene.gltf(
            filepath=str(d / f"{name}.glb"), export_format="GLB",
            export_vertex_color="ACTIVE", export_normals=True,
            export_materials="EXPORT", export_texcoords=True,
            export_apply=True, use_selection=True,
            export_yup=True, export_skins=False, export_animations=False,
            export_extras=True)

        # Restore selection state
        for o in ctx.scene.objects:
            o.select_set(False)
        for o in prev_selected:
            o.select_set(True)
        ctx.view_layer.objects.active = prev_active

    else:
        # Fallback: v1.1.0 behaviour — export entire scene, but exclude preview meshes
        prev_active   = ctx.view_layer.objects.active
        prev_selected = [o for o in ctx.scene.objects if o.select_get()]

        # Select everything except og_preview_mesh objects
        for o in ctx.scene.objects:
            o.select_set(False)
        export_objs = [o for o in ctx.scene.objects
                       if o.type == "MESH" and not o.get("og_preview_mesh")]
        for o in export_objs:
            o.select_set(True)
        if export_objs:
            ctx.view_layer.objects.active = export_objs[0]

        bpy.ops.export_scene.gltf(
            filepath=str(d / f"{name}.glb"), export_format="GLB",
            export_vertex_color="ACTIVE", export_normals=True,
            export_materials="EXPORT", export_texcoords=True,
            export_apply=True, use_selection=True,
            export_yup=True, export_skins=False, export_animations=False,
            export_extras=True)

        for o in ctx.scene.objects:
            o.select_set(False)
        for o in prev_selected:
            o.select_set(True)
        ctx.view_layer.objects.active = prev_active

    log("Exported GLB")
